version: '3.8'
services:
  mongo-db:
    image: mongo:6.0.6
    container_name: mongo-db-test
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./mongo-test:/data/db
    ports:
      - 27017:27017
  postgresql:
    image: postgres:15.3
    container_name: postgresql-test
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - ./postgres-test:/var/lib/postgresql/data
    ports:
      - 5432:5432
  ##crar un pgadmin
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-test
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@email.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - 8080:80
